---
- name: eve
  hosts: eveservers
  sudo: true

  tasks:
  - name: Install Python pip
    apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
    with_items:
      - build-essential
      - python-dev
      - python-pip

  - name: Install Eve
    pip: name=eve

  - name: Create opt directory if it doesn't exist.
    file:
      state: directory
      path: /opt/

  - name: Deploy source file
    copy: src=./src/main.py dest=/opt/main.py
